package:
  name: processflow
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/E3SM-Project/processflow.git
  git_tag: {{ environ['TAG'] }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  string: {{ environ['BUILD_NAME'] }}
  noarch: python

about:
    home: https://github.com/E3SM-Project/processflow
    summary: Automated post processing for E3SM model data

requirements:
  host:
    - python
    - pip
  
  run:
    - python
    - mpas-analysis >=1.2.5
    - nco >=4.8.1
    - e3sm_diags >=1.7.1
    - e3sm_to_cmip >=1.2.2
    - peewee >=3.10.0
    - configobj
    - beautifulsoup4
    - jinja2

test:
  imports:
    - processflow
  commands:
    - export CDAT_ANONYMOUS_LOG=no; processflow -h